name: doctors_appointment_application
description: "Patient Appointment booking application"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  carousel_slider: ^5.0.0
  uuid: ^4.5.1
  supabase_flutter: ^2.8.4
  platform: ^3.1.6
  universal_platform: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/